### ISSUE TITLE
Stride export broken

### ISSUE THREAD

**Issue by azeno** [vvvv/VL.StandardLibs#675]
It seems we're running into https://github.com/stride3d/stride/issues/2232 as well. 

**Which version are you experiencing the bug with?**
6.4

**Is there an earlier version where this still works?**
Unknown

**To Reproduce**
Export any Stride help patch

**Additional context**
```
Build started at 20:05...
1>------ Build started: Project: Explanation Overview 2d Primitives, Configuration: Debug Any CPU ------
1>C:\Users\rober\Documents\vvvv\gamma\Exports\src\Explanation Overview 2d Primitives\Explanation Overview 2d Primitives.csproj : warning NU1507: There are 3 package sources defined in your configuration. When using central package management, please map your package sources with package source mapping (https://aka.ms/nuget-package-source-mapping) or specify a single package source. The following sources are defined: vvvv-public-feed, [nuget.org](http://nuget.org/), Stride
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2401,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "Stride.Assets.Models", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2401,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\rober.nuget\packages\stride.importer.assimp\4.2.0.2121\lib\net8.0\Stride.Importer.Assimp.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2401,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\rober.nuget\packages\stride.importer.common\4.2.0.2121\lib\net8.0\Stride.Importer.Common.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2401,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\rober.nuget\packages\stride.assets.models\4.2.0.2121\lib\net8.0\Stride.Importer.FBX.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
1>CSC : warning WFAC010: Remove high DPI settings from C:\Users\rober\Documents\vvvv\gamma\Exports\src\Explanation Overview 2d Primitives\App.manifest and configure via Application.SetHighDpiMode API or 'ApplicationHighDpiMode' project property
1>Patch for assembly [Explanation Overview 2d Primitives, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]
1>Explanation Overview 2d Primitives -> C:\Users\rober\Documents\vvvv\gamma\Exports\src\Explanation Overview 2d Primitives\bin\Debug\Explanation Overview 2d Primitives.dll
1>Error restoring NuGet packages!
1>
1>==== Exception details ====
1>
1>System.AggregateException: One or more errors occurred. (Could not load file or assembly '[System.Security](http://system.security/).Cryptography.Pkcs, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.)
1> ---> [System.IO](http://system.io/).FileNotFoundException: Could not load file or assembly '[System.Security](http://system.security/).Cryptography.Pkcs, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
1>File name: '[System.Security](http://system.security/).Cryptography.Pkcs, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
1> at NuGet.Packaging.Signing.PrimarySignature.Load(Byte[] data)
1> at NuGet.Packaging.Signing.PrimarySignature.Load(Stream stream)
1> at NuGet.Packaging.PackageArchiveReader.GetPrimarySignatureAsync(CancellationToken token)
1> at NuGet.Packaging.Signing.PackageSignatureVerifier.VerifySignaturesAsync(ISignedPackageReader package, SignedPackageVerifierSettings settings, CancellationToken token, Guid parentId)
1> at NuGet.Packaging.PackageExtractor.VerifyPackageSignatureAsync(String source, Guid parentId, PackageIdentity package, PackageExtractionContext packageExtractionContext, ISignedPackageReader signedPackageReader, CancellationToken token)
1> at NuGet.Packaging.PackageExtractor.<>c__DisplayClass5_0.<<InstallFromSourceAsync>b__0>d.MoveNext()
1>--- End of stack trace from previous location ---
1> at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func2 action, CancellationToken token) 1>   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func2 action, CancellationToken token)
1> at NuGet.Packaging.PackageExtractor.InstallFromSourceAsync(PackageIdentity packageIdentity, IPackageDownloader packageDownloader, VersionFolderPathResolver versionFolderPathResolver, PackageExtractionContext packageExtractionContext, CancellationToken token, Guid parentId)
1> at NuGet.Commands.ProjectRestoreCommand.InstallPackageAsync(RemoteMatch installItem, NuGetv3LocalRepository userPackageFolder, PackageExtractionContext packageExtractionContext, CancellationToken token)
1> at NuGet.Commands.ProjectRestoreCommand.InstallPackagesAsync(HashSet1 uniquePackages, IEnumerable1 graphs, IList1 downloadDependencyInformations, NuGetv3LocalRepository userPackageFolder, CancellationToken token) 1>   at NuGet.Commands.ProjectRestoreCommand.TryRestoreAsync(LibraryRange projectRange, IEnumerable1 frameworkRuntimePairs, NuGetv3LocalRepository userPackageFolder, IReadOnlyList1 fallbackPackageFolders, RemoteDependencyWalker remoteWalker, RemoteWalkContext context, Boolean forceRuntimeGraphCreation, CancellationToken token, TelemetryActivity telemetryActivity, String telemetryPrefix) 1>   at NuGet.Commands.RestoreCommand.ExecuteRestoreAsync(NuGetv3LocalRepository userPackageFolder, IReadOnlyList1 fallbackPackageFolders, RemoteWalkContext context, CancellationToken token, TelemetryActivity telemetryActivity)
1> at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
1> at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
1> at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List1 restoreTasks) 1>   at NuGet.Commands.RestoreRunner.RunWithoutCommit(IEnumerable1 restoreRequests, RestoreArgs restoreContext)
1> --- End of inner exception stack trace ---
1> at Stride.Core.Assets.RestoreHelper.Restore(ILogger logger, NuGetFramework nugetFramework, String runtimeIdentifier, String packageName, VersionRange versionRange, String settingsRoot)
1> at Stride.Core.Assets.NuGetAssemblyResolver.<>c__DisplayClass5_0.<SetupNuGet>b__0(Object sender, ResolveEventArgs eventArgs)
1>
1>==== Log ====
1>
1>[Verbose] Running restore with 16 concurrent jobs.
1>[Verbose] Reading project file StrideNugetResolver.json.
1>[Information] Restoring packages for StrideNugetResolver.json...
1>[Verbose] Restoring packages for .NETCoreApp,Version=v8.0...
1>[Information] CACHE https://api.nuget.org/v3-flatcontainer/microsoft.extensions.primitives/index.json
1>[Information] CACHE [https://packages.stride3d.net/nuget/FindPackagesById()?id='Microsoft.Extensions.Primitives'&semVerLevel=2.0.0](https://packages.stride3d.net/nuget/FindPackagesById()?id=%27Microsoft.Extensions.Primitives%27&semVerLevel=2.0.0)
1>[Information] CACHE https://api.nuget.org/v3-flatcontainer/microsoft.extensions.primitives/6.0.0/microsoft.extensions.primitives.6.0.0.nupkg
1>[Verbose] Resolving conflicts for net8.0...
1>[Verbose] Acquiring lock for the installation of Microsoft.Extensions.Primitives 6.0.0
1>[Verbose] Acquired lock for the installation of Microsoft.Extensions.Primitives 6.0.0
1>[Verbose] Running restore with 16 concurrent jobs.
1>[Verbose] Reading project file StrideNugetResolver.json.
1>[Information] Restoring packages for StrideNugetResolver.json...
1>[Verbose] Restoring packages for .NETCoreApp,Version=v8.0...
1>[Verbose] Resolving conflicts for net8.0...
1>[Verbose] Acquiring lock for the installation of Microsoft.Extensions.Primitives 6.0.0
1>[Verbose] Acquired lock for the installation of Microsoft.Extensions.Primitives 6.0.0
1>
1>C:\Users\rober.nuget\packages\stride.core.assets.compilerapp\4.2.0.2121\buildTransitive\Stride.Core.Assets.CompilerApp.targets(153,5): error MSB3073: The command ""C:\Users\rober.nuget\packages\stride.core.assets.compilerapp\4.2.0.2121\buildTransitive..\lib\net8.0\Stride.Core.Assets.CompilerApp.exe" --disable-auto-compile --project-configuration "Debug" --platform=Windows --project-configuration=Debug --compile-property:StrideGraphicsApi=Direct3D11 --output-path="C:\Users\rober\Documents\vvvv\gamma\Exports\src\Explanation Overview 2d Primitives\bin\Debug\data" --build-path="C:\Users\rober\Documents\vvvv\gamma\Exports\src\Explanation Overview 2d Primitives\obj\stride\assetbuild\data" --package-file="C:\Users\rober\Documents\vvvv\gamma\Exports\src\Explanation Overview 2d Primitives\Explanation Overview 2d Primitives.csproj" --msbuild-uptodatecheck-filebase="C:\Users\rober\Documents\vvvv\gamma\Exports\src\Explanation Overview 2d Primitives\obj\Debug\stride\assetcompiler-uptodatecheck"" exited with code 1.
1>Done building project "Explanation Overview 2d Primitives.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 20:05 and took 15,561 seconds ==========
```

**Comment by azeno** [comment]
bd9657af03a916e2135d39cbfe8cdb8a8c612b6a
