### ISSUE TITLE
HelpBrowser does not work with --package-repositories VL.StandardLibs

### ISSUE THREAD

**Issue by kopffarben** [vvvv/VL.StandardLibs#683]
**Describe the bug**
When I work on the VL.StandardLibs and accordingly start VL with --package-repositories VL.StandardLibs, the Heplbrowser no longer works.

from the log
```
Failed to run handler of Help Browser
System.MissingMethodException: Method not found: 'Void _VL_Collections_.Collections.Spread._Operations_.GroupBy_Length(VL.Lib.Collections.Spread`1<!!0>, Int32, VL.Lib.Collections.Spread`1<VL.Lib.Collections.Spread`1<!!0>> ByRef, VL.Lib.Coll
ections.Spread`1<!!0> ByRef)'.
   at _HelpbrowserMPages_.HelpBrowser.Pages.Home.GettingStarted.Documentation.DocumentationView_Bobs83nyt4KODDjBfHBO1l.__Create__(NodeContext Node_Context)
   at _HelpbrowserMPages_.HelpBrowser.Pages.Home.GettingStarted.Documentation.DocumentationView_Bobs83nyt4KODDjBfHBO1l.Create(NodeContext Node_Context)
   at _HelpbrowserMPages_.HelpBrowser.Pages.Home.GettingStarted.Documentation_PidWIrcfheZPBqZ555yBLm.Update(IWidgetViewOperator_I Interaction_Operator_In, Column_C& Output_Out)
   at _HelpbrowserMPages_.HelpBrowser.Pages.Home.GettingStarted.GettingStarted_Blcpn6r4N2QNQ9N2FXTMnF.Update(RectangleF Bounds_In, Reference_C`1 State_In, BehaviorSubject`1 Content_In, IMouse Mouse_Device_In, ILayer& Layer_Out)
   at _HelpbrowserMPages_.HelpBrowser.Pages.Home.Home_CMjl8L2Y1bpP5QchjX1A5e.Update(IMouse Mouse_Device_In, Reference_C`1 State_In, BehaviorSubject`1 Content_In, RectangleF Bounds_In, ILayer& Output_Out)
   at _VL_UI_HelpBrowser_.HelpBrowser.App_Djk5Vm5YngbOC2s9n6XvNy.Update(IChannel`1 Focused_In, BehaviorSubject`1 Content_In, ILayer& Output_Out)
   at _VL_UI_HelpBrowser_.HelpBrowser.HelpBrowser_VDWmDkmaxTYLnP0S8RHP0r.Update(BehaviorSubject`1 Content_In, SkiaWindow& Output_Out)
   at _VL_UI_HelpBrowser_.HelpBrowser.HelpBrowserCommand_C.<>c__DisplayClass3_0.<Update>b__0(Object stateInput_17, Object& stateOutput_18, IWindow& window_19)
   at VL.HDE.WindowFactory.Update(String name, CreateHandler create, UpdateHandler update, Int32& activeWindowCount)
```

**Which version are you experiencing the bug with?**
i tested 6.7-0136 and some newer

**To Reproduce**
Starte VL via VS
Oder starte VL mit dem GammaLauncher und -package-repositories VL.StandardLibs,

**Comment by azeno** [comment]
Had a quick look using build 6.7-190 and it worked for "Normal startup". Any other one failed for me with a `ReflectionTypeLoadException` complaining it can't load `VL.Core.Skia`. No idea why. What did work for me was enabling the `WorkOnVLCore` switch in `all.csproj`.
